name: push

on:
  workflow_dispatch:
  push:
    branches: master
  pull_request:

permissions:
  contents: read

jobs:
  elisp-autofmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: purcell/setup-emacs@v7.0
        with:
          version: 30.2
      - run: git clone --depth=1 https://codeberg.org/ideasman42/emacs-elisp-autofmt.git
      - run: chmod +x ./emacs-elisp-autofmt/elisp-autofmt.py
      - run: git ls-files '*.el'|xargs -r ./emacs-elisp-autofmt/elisp-autofmt-cmd.py
      - run: git diff --exit-code
